### ISSUE TITLE
Completely suppresses channel registration in packets

### ISSUE THREAD

**Issue by Brickgard** [LoreSchaeffer/CustomF3Brand#7]
Due to how the [brand packet is overwritten](https://github.com/LoreSchaeffer/CustomF3Brand/blob/main/src/main/java/it/multicoredev/cf3b/velocity/PacketListenerChannelInitializer.java#L54), resources such as [Axiom](https://modrinth.com/plugin/axiom-paper-plugin) cannot communicate properly between a server plugin and client-side mods.
This creates incompatibilities with mods compatible with paper that communicate in this way.
This behavior also prevents plugin-triggered server transfers, such as [Skript's Connect Player to Proxy Server effect](https://skripthub.net/docs/?id=3157) and similar backend-server behaviors that communicate with the proxy in this way.

I'm unaware if there's a workaround for this that retains the F3 brand rewriting behavior, mainly wanted this documented in case others encounter a similar issue with mod-plugin communication channels simply not existing while using this resource.

**Comment by dirazi** [comment]
Experienced the same issue, tried to trace down why my backend servers weren't communicating with the proxy for about a week before being told to removed any F3 plugins I may have, sure enough this was the only plugin I disabled which brought back all plugin messaging functions.

**Comment by LoreSchaeffer** [comment]
First of all, sorry for a late response, i've been very busy with my main job.

As stated in the plugin description the velocity version in in alpha because not using that proxy i've been able to do only some simple tests on the plugin so thank you for your help.

I don't know if there is something i could do for client side mods that looks for a specific brand on the server.

Other plugin messages instead should be forwarded without any problems, so if it's not happening it surely a bug that i'll try to fix.

**Comment by LoreSchaeffer** [comment]
I've released 1.2.1 version that should fix some bug, let me know if it solves your problems

**Comment by Brickgard** [comment]
I cannot recreate any of these issues as of version 1.2.1, such as Axiom's packet registration on login or Skript connecting players between servers.
Very cool to see, I will continue testing and report if any other behavior arises as I re-implement it into my network.  Thanks for your work!

**Comment by LoreSchaeffer** [comment]
I'm glad to hear that. I'll mark this issue as closed
